const fs=require('fs');
const o=[];
const xml=fs.readFileSync('信用卡纠纷/信用卡纠纷/word/document.xml','utf8');
const bm=[];let m;
const r1=/w:bookmarkStart[^>]*?w:name="([^"]+)"/g;
while((m=r1.exec(xml))!==null)bm.push(m[1]);
o.push('bookmarks:'+bm.length);
bm.slice(0,20).forEach((n,i)=>o.push(i+':'+n));
const r2=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;
const u=[];while((m=r2.exec(xml))!==null)u.push(m[0]);
const uu=[...new Set(u)];
o.push('docx uuids:'+uu.length);
uu.slice(0,10).forEach((x,i)=>o.push(i+':'+x));
const mj=fs.readFileSync('信用卡纠纷/markData.json','utf8');
const mu=[];const r3=/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi;
while((m=r3.exec(mj))!==null)mu.push(m[0]);
const muu=[...new Set(mu)];
o.push('markData uuids:'+muu.length);
const ds=new Set(uu.map(x=>x.toLowerCase()));
let ov=0;muu.forEach(x=>{if(ds.has(x.toLowerCase()))ov++;});
o.push('overlap:'+ov+'/'+muu.length);
const i=xml.indexOf('bookmarkStart');
if(i>=0)o.push('ctx:'+xml.substring(i,i+200));
fs.writeFileSync('_result.txt',o.join('\n'),'utf8');
